export const SET_START_DATE = "SET_START_DATE";
export const SET_REPEAT_TYPE = "SET_REPEAT_TYPE";

export const SET_YEARLY_SUBTYPE = "SET_YEARLY_SUBTYPE";
export const SET_YEARLY_ARG2_MONTH = "SET_YEARLY_ARG2_MONTH";
export const SET_YEARLY_ARG2_MONTHDAY = "SET_YEARLY_ARG2_MONTHDAY";
export const SET_YEARLY_ARG3_SETPOS = "SET_YEARLY_ARG3_SETPOS";
export const SET_YEARLY_ARG3_DAY = "SET_YEARLY_ARG3_DAY";
export const SET_YEARLY_ARG3_MONTH = "SET_YEARLY_ARG3_MONTH";

export const SET_MONTHLY_INTERVAL = "SET_MONTHLY_INTERVAL";
export const SET_MONTHLY_SUBTYPE = "SET_MONTHLY_SUBTYPE";
export const SET_MONTHLY_ARG1_MONTHDAY = "SET_MONTHLY_ARG1_MONTHDAY";
export const SET_MONTHLY_ARG2_SETPOS = "SET_MONTHLY_ARG2_SETPOS";
export const SET_MONTHLY_ARG2_DAY = "SET_MONTHLY_ARG2_DAY";

export const SET_WEEKLY_INTERVAL = "SET_WEEKLY_INTERVAL";
export const SET_WEEKLY_DAYS = "SET_WEEKLY_DAYS";

export const SET_END_SUBTYPE = "SET_END_SUBTYPE";
export const SET_END_AFTER_INTERVAL = "SET_END_AFTER_INTERVAL";
export const SET_END_ON_DATE = "SET_END_ON_DATE";
